// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQHmiAvG5Il0QgR1Ue0nTIQJzR-wsWGII',
    appId: '1:504949298910:web:e4c02e63f79b39d352d44f',
    messagingSenderId: '504949298910',
    projectId: 'winematch-96637',
    authDomain: 'winematch-96637.firebaseapp.com',
    storageBucket: 'winematch-96637.appspot.com',
    measurementId: 'G-QBC9CZJZ2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVm3ZkTecbxJm7haj0zdWYtQlLH-Ojwk',
    appId: '1:504949298910:android:3e4f9d2063a2f6f052d44f',
    messagingSenderId: '504949298910',
    projectId: 'winematch-96637',
    storageBucket: 'winematch-96637.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1sGZTNMdHLbrvoQZj3mrg-KxJ49w1HDM',
    appId: '1:504949298910:ios:8bc1ceac4cd99b0452d44f',
    messagingSenderId: '504949298910',
    projectId: 'winematch-96637',
    storageBucket: 'winematch-96637.appspot.com',
    iosClientId: '504949298910-oodo8213cp25spr2c3fs8d47f8abmpmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.winematch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1sGZTNMdHLbrvoQZj3mrg-KxJ49w1HDM',
    appId: '1:504949298910:ios:8bc1ceac4cd99b0452d44f',
    messagingSenderId: '504949298910',
    projectId: 'winematch-96637',
    storageBucket: 'winematch-96637.appspot.com',
    iosClientId: '504949298910-oodo8213cp25spr2c3fs8d47f8abmpmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.winematch',
  );
}
